FROM ollama/ollama

# 无需设置环境变量
# ENV OLLAMA_HOST="0.0.0.0"
# ENV OLLAMA_MODELS="/models"

# 运行 Ollama
CMD ["ollama", "start"]

# 命令行构建
# docker build -t sad_ollama .

# 命令行运行
# docker run -d --name sad_ollama_container \
#   -p 11434:11434 \
#   -v ollama:/root/.ollama \
#   sad_ollama
